audit_header: false
title: CaPeesh Consulting LLC Video Blog with Charletta Wilson
description: Our mission is to be the best resource for whole-person leadership development. Whether you are a small or family-owned business, government or corporate leader, our team can answer any questions you might have around leading with heart.
show_custom_links: true
custom_links:
  - title: Events
    url: https://www.eventbrite.com/o/charletta-wilson-phd-acc-certified-dare-to-leadtm-facilitator-20060596036
  - title: Coaching
    url: https://capeeshconsulting.com/coaching/
  - title: Contact
    url: https://capeeshconsulting.com/contact/   
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Charletta Wilson
  title:
  license_number:
  about_markdown: |
    Charletta is an industrial & organizational psychologist, Certified Mindfulness Coach, Certified Dare to Lead™ Facilitator and educator of graduate studies in leadership. For over two decades, she’s worked collaboratively with hundreds of clients in business startups, leadership development and most recent, growing 'brave teams'. Charletta serves as an executive coach to senior leaders in government and corporations. Her passion is to help leaders grow awareness and capacity for courage and creativity which comes through CaPeesh™ .

    CaPeesh™ is a bold expression 'You understand?!' The beginning of wisdom, begins with understanding. At CaPeesh we help leaders understand, practice and become. We don't just talk leadership, we show you how!
  brand: CaPeesh Consulting
  brokerage:
  market:
  address: P.O. Box 63074 Ewa Beach, HI 96706
  phone:
  phone_type:
  phone2:
  phone2_type:
  email: Info@capeeshconsulting.com
  url: https://capeeshconsulting.com

CTAs:
  first_CTA_text: Start Now
  first_CTA_URL: https://capeeshconsulting.com/contact/
  second_CTA_text: Dare to Lead
  second_CTA_URL: https://capeeshconsulting.com/dare-to-lead/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Get started with me"
    CTA_text: Interested in learning more? Contact us!
    CTA_link_text: "Start Now"
    CTA_url: https://capeeshconsulting.com/contact/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Dare to Lead™ Training"
    CTA_text2: "Brave work. Tough conversations. Whole-hearted leadership."
    CTA_link_text2: "Dare to Lead"
    CTA_url2: https://capeeshconsulting.com/dare-to-lead/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/capeeshconsulting/
  linkedin_url: https://www.linkedin.com/in/capeesh/
  youtube_url: https://www.youtube.com/channel/UC00OCdx8Ccsl6ZbmEKa8Gmg
  twitter_url:
  instagram_url: https://www.instagram.com/capeeshconsulting/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with Charletta Wilson'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from CaPeesh Consulting - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Charletta Wilson'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text:
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#2a85c7'
  theme_color: '#bfbfbf'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 2px
  w_shadow: 4px
  shadow_spread: 7px
  shadow_color: '#ffa42f'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#8ac53f'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
